filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/out.log       # Đường dẫn tới file log trong container Go
    fields:
      service: golang-elk
  # THÊM CÁC DÒNG NÀY VÀO:
# XÓA KHỐI "grok" CŨ VÀ THAY BẰNG KHỐI "dissect" NÀY:
# THAY THẾ BẰNG KHỐI NÀY:
    processors:
      - dissect:
          # Dùng "tokenizer" (số ít) và 1 pattern duy nhất
          tokenizer: 'time="%{@timestamp}" level=%{log.level} msg="%{message}"'
          
          # Chỉ định trường cần bóc tách
          field: "message" 
          
          # Bỏ qua nếu dòng log không khớp
          ignore_failure: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"] # Gửi log sang container Elasticsearch
  username: "elastic"
  password: "changeme"          # Mặc định trong môi trường dev

setup.kibana:
  host: "kibana:5601"

setup.template.enabled: true
setup.template.name: "golang-elk"
setup.template.pattern: "golang-elk-*"
