filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/out.log
    fields:
      service: golang-elk
    
    # BỘ XỬ LÝ GROK (REGEX)
    # Nó sẽ thử bóc tách log bằng Pattern 1, nếu thất bại, nó thử Pattern 2
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"] 
  username: "elastic"
  password: "changeme"          

setup.kibana:
  host: "kibana:5601"

setup.template.enabled: true
setup.template.name: "golang-elk"
setup.template.pattern: "golang-elk-*"