version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

  golang-elk:
    build:
      context: ./golangcollectlog   # 👉 trỏ đúng thư mục có Dockerfile
      dockerfile: Dockerfile        # 👉 tên file Dockerfile trong thư mục đó
    container_name: golang-elk
    ports:
      - "8080:8080"
    volumes:
      - ./golangcollectlog/logs:/app/logs  # Mount logs đúng thư mục con
    depends_on:
      - elasticsearch
    networks:
      - elk
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./golangcollectlog/logs:/app/logs:ro
    command: ["--strict.perms=false"]
    depends_on:
      - elasticsearch
      - golang-elk
    networks:
      - elk


networks:
  elk:
    driver: bridge
